version: "3"
services:
  pg:
    image: "postgres:latest"
    container_name: pg
    env_file:
      - ./backend/.env.production
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
  pg-development:
    image: "postgres:latest"
    container_name: pg-development
    env_file:
      - ./backend/.env.development
    ports:
      - 5433:5432
    volumes:
      - pg-development-data:/var/lib/postgresql/data/
  redis:
    image: "redis:latest"
    container_name: redis
    env_file:
      - ./backend/.env.production
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  pg-data:
  redis-data:
  pg-development-data:
